language: java
jdk:
  - openjdk8
  - openjdk11
services:
  - docker
before_install:
#  - sudo chown -R travis ./pull_client_image.sh
#  - sudo chmod +x ./pull_client_image.sh
#  - ./pull_client_image.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull wimill/accurev:latest
  - docker-compose -f ./src/docker/docker-compose.yml up -d
#  - docker exec -it accurev-client /tmp/accurev-7.3-linux-x64-clientonly.bin -i silent -f installer.properties
#  - docker cp . accurev-client:accurev-project/
script:
#  - docker exec -it accurev-client accurev-project/gradlew clean assemble check jacocoTestReport
  - ./gradlew clean spotlessApply assemble check jacocoTestReport jpi shadowJar
after_success:
#  - docker cp accurev-client:accuerv-project/build/jacoco build/jacoco
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $api_key
  file:
    - build/libs/accurev-client.hpi
    - build/libs/accurev-client-plugin-1.0.0-SNAPSHOT-all.jar
  skip_cleanup: true
  draft: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
