version: "3.3"
services:
  accurev:
    image: ehhnwidex/accurev
    ports:
      - "5050:5050"
    healthcheck:
      test: ./accurev/bin/accurev info
      interval: 1m
      timeout: 10s
      retries: 5
  accurev2:
    image: ehhnwidex/accurev
    ports:
      - "5051:5050"